would_you_rather_questions = {
    "Would you rather always be 10 minutes late or always be 20 minutes early?": {"option1": "10 minutes late", "option2": "20 minutes early"},
    "Would you rather have the ability to fly or be invisible?": {"option1": "fly", "option2": "be invisible"},
    "Would you rather only be able to whisper or only be able to shout?": {"option1": "whisper", "option2": "shout"},
    "Would you rather live without music or live without movies?": {"option1": "live without music", "option2": "live without movies"},
    "Would you rather be able to speak all languages or be able to talk to animals?": {"option1": "speak all languages", "option2": "talk to animals"},
    "Would you rather never use social media again or never watch another movie?": {"option1": "never use social media again", "option2": "never watch another movie"},
    "Would you rather always have to tell the truth or always have to lie?": {"option1": "always tell the truth", "option2": "always lie"},
    "Would you rather have a pause button for your life or a rewind button?": {"option1": "pause button", "option2": "rewind button"},
    "Would you rather be able to teleport anywhere or be able to read minds?": {"option1": "teleport anywhere", "option2": "read minds"},
    "Would you rather have unlimited pizza or unlimited tacos?": {"option1": "unlimited pizza", "option2": "unlimited tacos"},
    "Would you rather always have perfect weather or always have your favorite food available?": {"option1": "perfect weather", "option2": "favorite food available"},
    "Would you rather never have to sleep or never have to eat?": {"option1": "never have to sleep", "option2": "never have to eat"},
    "Would you rather be the funniest person alive or the smartest person alive?": {"option1": "be the funniest person alive", "option2": "be the smartest person alive"},
    "Would you rather be able to time travel to the past or to the future?": {"option1": "time travel to the past", "option2": "time travel to the future"},
    "Would you rather have a home on the beach or a home in the mountains?": {"option1": "home on the beach", "option2": "home in the mountains"},
    "Would you rather only be able to eat sweet food or only be able to eat savory food?": {"option1": "eat sweet food", "option2": "eat savory food"},
    "Would you rather be famous for your talent or rich for your business?": {"option1": "be famous for your talent", "option2": "be rich for your business"},
    "Would you rather have a super-strong body or a super-fast mind?": {"option1": "super-strong body", "option2": "super-fast mind"},
    "Would you rather be stuck on a desert island alone or with someone you dislike?": {"option1": "alone on a desert island", "option2": "with someone you dislike"},
    "Would you rather be able to control the weather or control technology?": {"option1": "control the weather", "option2": "control technology"},
    "Would you rather never be able to use a smartphone again or never be able to use a computer again?": {"option1": "never use a smartphone again", "option2": "never use a computer again"},
    "Would you rather explore outer space or the deep ocean?": {"option1": "explore outer space", "option2": "explore the deep ocean"},
    "Would you rather be able to draw anything perfectly or play any instrument perfectly?": {"option1": "draw anything perfectly", "option2": "play any instrument perfectly"},
    "Would you rather always have clean clothes or always have a clean house?": {"option1": "always have clean clothes", "option2": "always have a clean house"},
    "Would you rather have a personal robot assistant or a personal chef?": {"option1": "have a personal robot assistant", "option2": "have a personal chef"},
    "Would you rather never feel cold again or never feel hot again?": {"option1": "never feel cold again", "option2": "never feel hot again"},
    "Would you rather be able to breathe underwater or survive without food for 30 days?": {"option1": "breathe underwater", "option2": "survive without food for 30 days"},
    "Would you rather spend a year traveling the world or a year getting paid to stay home?": {"option1": "spend a year traveling the world", "option2": "spend a year getting paid to stay home"},
    "Would you rather have unlimited free books or unlimited free movies?": {"option1": "unlimited free books", "option2": "unlimited free movies"},
    "Would you rather be able to run at 100 mph or jump 100 feet high?": {"option1": "run at 100 mph", "option2": "jump 100 feet high"},
    "Would you rather always have to dress formally or always have to dress casually?": {"option1": "always dress formally", "option2": "always dress casually"},
    "Would you rather be able to remember every detail of your life or forget every bad memory?": {"option1": "remember every detail of your life", "option2": "forget every bad memory"},
    "Would you rather never have to wait in line again or never have to pay for parking?": {"option1": "never wait in line again", "option2": "never pay for parking"},
    "Would you rather have a pet dragon or a pet unicorn?": {"option1": "have a pet dragon", "option2": "have a pet unicorn"},
    "Would you rather be able to change one event in history or see one future event?": {"option1": "change one event in history", "option2": "see one future event"},
    "Would you rather live in a world without books or a world without the internet?": {"option1": "live without books", "option2": "live without the internet"},
    "Would you rather always have a perfect selfie or always have perfect cooking?": {"option1": "always have a perfect selfie", "option2": "always have perfect cooking"},
    "Would you rather have a job you love with low pay or a job you hate with high pay?": {"option1": "have a job you love with low pay", "option2": "have a job you hate with high pay"},
    "Would you rather never have to do laundry again or never have to do dishes again?": {"option1": "never do laundry again", "option2": "never do dishes again"},
    "Would you rather be able to go anywhere in the world for free or eat anywhere in the world for free?": {"option1": "go anywhere in the world for free", "option2": "eat anywhere in the world for free"},
    "Would you rather have a house made of chocolate or a house made of clouds?": {"option1": "have a house made of chocolate", "option2": "have a house made of clouds"},
    "Would you rather be able to hear other people’s thoughts or have them hear yours?": {"option1": "hear other people’s thoughts", "option2": "have them hear yours"},
    "Would you rather always know the time or always know the weather?": {"option1": "always know the time", "option2": "always know the weather"},
    "Would you rather have an extra hour every day or an extra day every week?": {"option1": "have an extra hour every day", "option2": "have an extra day every week"},
    "Would you rather be the hero of a story or the villain of a story?": {"option1": "be the hero of a story", "option2": "be the villain of a story"},
    "Would you rather only be able to wear one color for the rest of your life or change colors every day?": {"option1": "wear one color forever", "option2": "change colors every day"},
    "Would you rather be able to control plants or control fire?": {"option1": "control plants", "option2": "control fire"},
    "Would you rather never have to go to the doctor again or never have to go to the dentist again?": {"option1": "never go to the doctor again", "option2": "never go to the dentist again"},
    "Would you rather only be able to use a bicycle or only be able to use public transit?": {"option1": "use a bicycle", "option2": "use public transit"},
    "Would you rather always have the newest tech gadgets or always have the best clothes?": {"option1": "have the newest tech gadgets", "option2": "have the best clothes"},
    "Would you rather be able to taste colors or see sounds?": {"option1": "taste colors", "option2": "see sounds"},
    "Would you rather have a personal library or a personal theater?": {"option1": "have a personal library", "option2": "have a personal theater"},
    "Would you rather eat only breakfast food or eat only dinner food for the rest of your life?": {"option1": "eat only breakfast food", "option2": "eat only dinner food"},
    "Would you rather never forget a face or never forget a name?": {"option1": "never forget a face", "option2": "never forget a name"},
    "Would you rather always get free coffee or always get free snacks?": {"option1": "always get free coffee", "option2": "always get free snacks"},
    "Would you rather be able to change your appearance at will or change your voice at will?": {"option1": "change your appearance at will", "option2": "change your voice at will"},
    "Would you rather have wings like a bird or gills like a fish?": {"option1": "have wings like a bird", "option2": "have gills like a fish"},
    "Would you rather only be able to watch comedies or only be able to watch dramas?": {"option1": "watch comedies", "option2": "watch dramas"},
    "Would you rather have a garden full of flowers or a garden full of fruits?": {"option1": "have a garden full of flowers", "option2": "have a garden full of fruits"},
    "Would you rather be able to teleport to the past or instantly learn any skill?": {"option1": "teleport to the past", "option2": "instantly learn any skill"},
    "Would you rather have a photographic memory or perfect musical pitch?": {"option1": "have a photographic memory", "option2": "have perfect musical pitch"},
    "Would you rather always know when someone is lying or always be able to persuade others?": {"option1": "always know when someone is lying", "option2": "always be able to persuade others"},
    "Would you rather be able to breathe fire or freeze things with a touch?": {"option1": "breathe fire", "option2": "freeze things with a touch"},
    "Would you rather never have to clean your room or never have to make your bed?": {"option1": "never have to clean your room", "option2": "never have to make your bed"},
    "Would you rather have a private island or a private spaceship?": {"option1": "have a private island", "option2": "have a private spaceship"},
    "Would you rather be able to speak to the past or speak to the future?": {"option1": "speak to the past", "option2": "speak to the future"},
    "Would you rather live where it is always daytime or always nighttime?": {"option1": "live where it is always daytime", "option2": "live where it is always nighttime"},
    "Would you rather have unlimited movie tickets or unlimited concert tickets?": {"option1": "have unlimited movie tickets", "option2": "have unlimited concert tickets"},
    "Would you rather be able to fly for one hour a day or become invisible for one hour a day?": {"option1": "fly for one hour a day", "option2": "become invisible for one hour a day"},
    "Would you rather have free access to any museum or free access to any amusement park?": {"option1": "have free access to any museum", "option2": "have free access to any amusement park"},
    "Would you rather have a pet dinosaur or a pet robot?": {"option1": "have a pet dinosaur", "option2": "have a pet robot"},
    "Would you rather have the power to heal others or the power to teleport yourself?": {"option1": "have the power to heal others", "option2": "have the power to teleport yourself"},
    "Would you rather always have great hair or always have great skin?": {"option1": "always have great hair", "option2": "always have great skin"},
    "Would you rather be on a tropical beach vacation or a snowy mountain vacation?": {"option1": "go on a tropical beach vacation", "option2": "go on a snowy mountain vacation"},
    "Would you rather have a time machine or a magic mirror?": {"option1": "have a time machine", "option2": "have a magic mirror"},
    "Would you rather only eat your favorite food and get tired of it or eat new foods forever?": {"option1": "eat your favorite food and get tired of it", "option2": "eat new foods forever"},
    "Would you rather be a famous author or a famous actor?": {"option1": "be a famous author", "option2": "be a famous actor"},
    "Would you rather be able to breathe in space or live forever under water?": {"option1": "breathe in space", "option2": "live forever under water"},
    "Would you rather have a never-ending supply of art supplies or tools?": {"option1": "have a never-ending supply of art supplies", "option2": "have a never-ending supply of tools"},
    "Would you rather always know the best route or always know the best deal?": {"option1": "always know the best route", "option2": "always know the best deal"},
    "Would you rather have your dream job and work too much or a boring job and work less?": {"option1": "have your dream job and work too much", "option2": "have a boring job and work less"},
    "Would you rather be able to rewind to fix mistakes or fast-forward to skip waiting?": {"option1": "rewind to fix mistakes", "option2": "fast-forward to skip waiting"},
    "Would you rather always get perfect gifts or always give perfect gifts?": {"option1": "always get perfect gifts", "option2": "always give perfect gifts"},
    "Would you rather have a car that drives itself or a house that cleans itself?": {"option1": "have a car that drives itself", "option2": "have a house that cleans itself"},
    "Would you rather be the best at one thing or good at many things?": {"option1": "be the best at one thing", "option2": "be good at many things"},
    "Would you rather never have to pay for clothes or never have to pay for food?": {"option1": "never pay for clothes", "option2": "never pay for food"},
    "Would you rather have a backyard roller coaster or a personal movie theater?": {"option1": "have a backyard roller coaster", "option2": "have a personal movie theater"},
    "Would you rather explore a jungle or explore a desert?": {"option1": "explore a jungle", "option2": "explore a desert"},
    "Would you rather have unlimited battery life for your devices or unlimited storage?": {"option1": "have unlimited battery life", "option2": "have unlimited storage"},
    "Would you rather be able to fly like Superman or be as strong as the Hulk?": {"option1": "fly like Superman", "option2": "be as strong as the Hulk"},
    "Would you rather only be able to read books on paper or only on a screen?": {"option1": "read books on paper", "option2": "read books on a screen"},
    "Would you rather always have your favorite season or always have your favorite holiday?": {"option1": "have your favorite season", "option2": "have your favorite holiday"},
    "Would you rather have a pet phoenix or a pet griffin?": {"option1": "have a pet phoenix", "option2": "have a pet griffin"},
    "Would you rather have a city-sized treehouse or a submarine mansion?": {"option1": "have a city-sized treehouse", "option2": "have a submarine mansion"},
    "Would you rather never have to do homework again or never have to pay taxes?": {"option1": "never do homework again", "option2": "never pay taxes"},
    "Would you rather be able to travel at the speed of sound or the speed of light?": {"option1": "travel at the speed of sound", "option2": "travel at the speed of light"},
    "Would you rather have a picnic in the clouds or a picnic on the moon?": {"option1": "have a picnic in the clouds", "option2": "have a picnic on the moon"},
    "Would you rather have a personal spaceship or a personal submarine?": {"option1": "have a personal spaceship", "option2": "have a personal submarine"},
    "Would you rather be able to control your dreams or remember every dream?": {"option1": "control your dreams", "option2": "remember every dream"},
    "Would you rather never have bad hair days or never have bad skin days?": {"option1": "never have bad hair days", "option2": "never have bad skin days"},
    "Would you rather have a musical talent or a sports talent?": {"option1": "have a musical talent", "option2": "have a sports talent"},
    "Would you rather be able to change the color of anything or change the shape of anything?": {"option1": "change the color of anything", "option2": "change the shape of anything"},
    "Would you rather always have fresh fruit or always have fresh pastries?": {"option1": "always have fresh fruit", "option2": "always have fresh pastries"},
    "Would you rather ride a dragon or fly on a jetpack?": {"option1": "ride a dragon", "option2": "fly on a jetpack"},
    "Would you rather have a garden that grows any food or a fridge that restocks itself?": {"option1": "have a garden that grows any food", "option2": "have a fridge that restocks itself"},
    "Would you rather be the smartest person in the room or the most charming person in the room?": {"option1": "be the smartest person in the room", "option2": "be the most charming person in the room"},
    "Would you rather have magical shoes or a magical hat?": {"option1": "have magical shoes", "option2": "have a magical hat"},
    "Would you rather be able to speak with machines or speak with plants?": {"option1": "speak with machines", "option2": "speak with plants"},
    "Would you rather have a library that never runs out of books or a playground that never runs out of games?": {"option1": "have a library that never runs out of books", "option2": "have a playground that never runs out of games"},
    "Would you rather have perfect balance or perfect coordination?": {"option1": "have perfect balance", "option2": "have perfect coordination"},
    "Would you rather know every recipe or know every language?": {"option1": "know every recipe", "option2": "know every language"},
    "Would you rather have a phone that never loses signal or a laptop that never runs out of battery?": {"option1": "have a phone that never loses signal", "option2": "have a laptop that never runs out of battery"},
    "Would you rather have a magic backpack or a magic pair of shoes?": {"option1": "have a magic backpack", "option2": "have a magic pair of shoes"},
    "Would you rather be able to explore space or explore ancient ruins?": {"option1": "explore space", "option2": "explore ancient ruins"},
    "Would you rather have a fountain that pours your favorite drink or a toaster that cooks your favorite breakfast?": {"option1": "have a fountain that pours your favorite drink", "option2": "have a toaster that cooks your favorite breakfast"},
    "Would you rather have a vacation home in the woods or a vacation home in the city?": {"option1": "have a vacation home in the woods", "option2": "have a vacation home in the city"},
    "Would you rather always have a fast internet connection or always have a comfortable chair?": {"option1": "always have a fast internet connection", "option2": "always have a comfortable chair"},
    "Would you rather be able to solve any math problem or write any story?": {"option1": "be able to solve any math problem", "option2": "be able to write any story"},
    "Would you rather have the power of super speed or the power of super strength?": {"option1": "have the power of super speed", "option2": "have the power of super strength"},
    "Would you rather have a magical garden or a magical kitchen?": {"option1": "have a magical garden", "option2": "have a magical kitchen"},
    "Would you rather never have to worry about money or never have to worry about health?": {"option1": "never have to worry about money", "option2": "never have to worry about health"},
    "Would you rather only be able to drink water or only be able to drink juice?": {"option1": "only drink water", "option2": "only drink juice"},
    "Would you rather have a robot best friend or a dragon best friend?": {"option1": "have a robot best friend", "option2": "have a dragon best friend"},
    "Would you rather be able to stay awake forever or fall asleep instantly whenever you want?": {"option1": "stay awake forever", "option2": "fall asleep instantly whenever you want"},
    "Would you rather have a house that changes color or a house that changes shape?": {"option1": "have a house that changes color", "option2": "have a house that changes shape"},
    "Would you rather have a bicycle that can fly or a skateboard that can float?": {"option1": "have a bicycle that can fly", "option2": "have a skateboard that can float"},
    "Would you rather have breakfast served in bed every day or dinner served on a rooftop every night?": {"option1": "have breakfast served in bed every day", "option2": "have dinner served on a rooftop every night"},
    "Would you rather be able to stop time for 10 seconds or make one wish come true?": {"option1": "stop time for 10 seconds", "option2": "make one wish come true"},
    "Would you rather be an expert in one hobby or decent in ten hobbies?": {"option1": "be an expert in one hobby", "option2": "be decent in ten hobbies"},
    "Would you rather always travel with a suitcase full of snacks or a suitcase full of books?": {"option1": "travel with a suitcase full of snacks", "option2": "travel with a suitcase full of books"},
    "Would you rather be able to paint with your mind or compose music with your thoughts?": {"option1": "paint with your mind", "option2": "compose music with your thoughts"},
    "Would you rather have a phone charger that never breaks or headphones that never tangle?": {"option1": "have a phone charger that never breaks", "option2": "have headphones that never tangle"},
    "Would you rather live in a treehouse or live in a castle?": {"option1": "live in a treehouse", "option2": "live in a castle"},
    "Would you rather have a garage full of bicycles or a garage full of scooters?": {"option1": "have a garage full of bicycles", "option2": "have a garage full of scooters"},
    "Would you rather always get front row seats or always get backstage passes?": {"option1": "always get front row seats", "option2": "always get backstage passes"},
    "Would you rather only be able to watch animated films or only be able to watch live-action films?": {"option1": "watch animated films", "option2": "watch live-action films"},
    "Would you rather have a magical scarf or a magical pair of gloves?": {"option1": "have a magical scarf", "option2": "have a magical pair of gloves"},
    "Would you rather have a waterfall in your backyard or a treehouse in your backyard?": {"option1": "have a waterfall in your backyard", "option2": "have a treehouse in your backyard"},
    "Would you rather always be able to find your keys or always be able to find your phone?": {"option1": "always be able to find your keys", "option2": "always be able to find your phone"},
    "Would you rather have the ability to breathe in any environment or the ability to survive any climate?": {"option1": "breathe in any environment", "option2": "survive any climate"},
    "Would you rather be able to always find lost items or always remember important dates?": {"option1": "always find lost items", "option2": "always remember important dates"},
    "Would you rather have a concert in your living room or a movie premiere in your kitchen?": {"option1": "have a concert in your living room", "option2": "have a movie premiere in your kitchen"},
    "Would you rather live in a world where it is always autumn or always spring?": {"option1": "live in a world where it is always autumn", "option2": "live in a world where it is always spring"},
    "Would you rather have a teleportation device or a shape-shifting hat?": {"option1": "have a teleportation device", "option2": "have a shape-shifting hat"},
    "Would you rather have a daily surprise or a weekly treat?": {"option1": "have a daily surprise", "option2": "have a weekly treat"},
    "Would you rather always know your next meal or always know your next destination?": {"option1": "always know your next meal", "option2": "always know your next destination"},
    "Would you rather have a tree that grows candy or a tree that grows toys?": {"option1": "have a tree that grows candy", "option2": "have a tree that grows toys"},
    "Would you rather have the ability to paint the sky or draw on the ground?": {"option1": "paint the sky", "option2": "draw on the ground"},
    "Would you rather never have to move again or never have to change your routine?": {"option1": "never have to move again", "option2": "never have to change your routine"},
    "Would you rather have a library that tells stories or a playground that tells jokes?": {"option1": "have a library that tells stories", "option2": "have a playground that tells jokes"},
    "Would you rather have a wardrobe that changes every day or shoes that adapt to your mood?": {"option1": "have a wardrobe that changes every day", "option2": "have shoes that adapt to your mood"},
    "Would you rather have a magical pen or a magical notebook?": {"option1": "have a magical pen", "option2": "have a magical notebook"},
    "Would you rather be able to hear music in silence or see colors in the dark?": {"option1": "hear music in silence", "option2": "see colors in the dark"},
    "Would you rather have a never-ending bubble bath or a never-ending pizza?": {"option1": "have a never-ending bubble bath", "option2": "have a never-ending pizza"},
    "Would you rather have a private concert or a private art gallery opening?": {"option1": "have a private concert", "option2": "have a private art gallery opening"},
    "Would you rather have a spaceship that can land anywhere or a train that can travel underwater?": {"option1": "have a spaceship that can land anywhere", "option2": "have a train that can travel underwater"},
    "Would you rather have a festival every weekend or a holiday every month?": {"option1": "have a festival every weekend", "option2": "have a holiday every month"}
}

from vote_app.models import Question, SessionLocal
db = SessionLocal()
for i in would_you_rather_questions:
    question = Question(question_text=i, option1=would_you_rather_questions[i]["option1"], option2=would_you_rather_questions[i]["option2"])
    db.add(question)

db.commit()
db.close